# Generated by Django 5.1.1 on 2024-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='daily_heighest_bottles',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='reply_bottles',
            field=models.BooleanField(default=False),
        ),
    ]
