# Generated by Django 5.1.1 on 2024-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_player_read_bottles'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_read_bottles',
            field=models.IntegerField(default=0),
        ),
    ]
