# Generated by Django 5.1.1 on 2024-09-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToBuyBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('radius', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bottle',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bottle',
            name='radius',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='bottle',
            name='bought_bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought', to='bottle.tobuybottle'),
        ),
    ]
