# Generated by Django 5.1.1 on 2024-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0002_tobuybottle_bottle_price_bottle_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
