# Generated by Django 5.1.1 on 2024-09-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0004_alter_bottle_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='radius',
        ),
    ]
