# Generated by Django 5.1.1 on 2024-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle', '0005_remove_bottle_price_remove_bottle_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
